Repository beyond-sw-camp/be08-fin-EasyCheck-EasyStay-front-client, pull requests merged in 2024-11, with the labels that each got.

#177 [feat/#173] 객실 예약 시 로그인 검증
  src/views/Reservation/Sections/ReservationForm.vue
  src/views/Reservation/Sections/RoomSelectionGrid.vue
Labels: Feat, Frontend

#179 [refactor/#178] 객실 요금 출력 방식 수정
  src/views/Reservation/Sections/RoomSelectionGrid.vue
Labels: Frontend, Refactor

#181 [refactor/#178] 객실 예약 결제 수정
  src/stores/reservationStore.js
Labels: Frontend, Refactor

#183 [desing/#176] 마이페이지 객실 환불 기능 추가 / 회원정보수정 기능 수정
  src/router/index.js
  src/stores/mypageStore.js
  src/stores/paymentStore.js
  src/views/Mypage/InfoUpdate/InfoCompleteView.vue
  src/views/Mypage/InfoUpdate/Sections/MemberInfoUpdate.vue
  src/views/Mypage/RoomReservationList/RoomReservationDetailView.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationDetailView.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
Labels: Feat, Design, Frontend

#182 [design/#164] 메뉴바 수정
  src/examples/navbars/NavbarDefault.vue
Labels: Design, Frontend

#187 [feat/#184] 객실 예약 내역 환불 연동
  src/stores/reservationStore.js
  src/views/Mypage/RoomReservationList/RoomReservationDetailView.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
Labels: Feat, Design, Frontend

#189 [feat/#188] 테마파크 환불
  src/stores/loginStore.js
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationDetailView.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
Labels: Feat, Frontend

#186 design: 간편예약 퍼블리싱
  src/assets/img/eventBanner 1.png
  src/assets/img/eventBanner 2.png
  src/assets/img/eventBanner 3.png
  src/assets/img/eventBanner 4.png
  src/assets/img/eventBanner 5.png
  src/assets/img/suggestionPoster.png
  src/examples/footers/FooterDefault.vue
  src/stores/reservationStore.js
  src/views/Events/EventsListView.vue
  src/views/Presentation/Sections/SearchRoom/RoomSearchForm.vue
Labels: Design, Frontend

#193 [feat/#190] 아이디 찾기 연동
  src/stores/loginStore.js
  src/views/LandingPages/SignIn/Member/FindMemberID/FindIdView.vue
  src/views/LandingPages/SignIn/Member/FindMemberID/IdAuthentication.vue
Labels: Feat, Design, Frontend

#195 [feat/#194] 비밀번호 찾기 연동
  src/stores/loginStore.js
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwAuthenticationView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwView.vue
  src/views/LandingPages/SignIn/Sections/PwAuthentication.vue
Labels: Feat, Frontend

#197 [refactor/#196] 마이페이지 리팩토링
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/LandingPages/SignIn/Corporate/CorporateJoinCompleteView.vue
  src/views/LandingPages/SignIn/Corporate/CorporateView.vue
  src/views/LandingPages/SignIn/Member/FindMemberID/FindIdAuthenticationView.vue
  src/views/LandingPages/SignIn/Member/FindMemberID/FindIdView.vue
  src/views/LandingPages/SignIn/Member/FindMemberID/IdAuthentication.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwAuthenticationView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/PwComplete.vue
  src/views/LandingPages/SignIn/Member/MemberView.vue
  src/views/LandingPages/SignIn/Sections/Authentication.vue
  src/views/LandingPages/SignIn/Sections/CorporateInfo.vue
  src/views/LandingPages/SignIn/Sections/MemberInfo.vue
  src/views/LandingPages/SignIn/Sections/Modal.vue
  src/views/LandingPages/SignIn/Sections/PwAuthentication.vue
  src/views/LandingPages/SignIn/SignUp/JoinCompleteView.vue
  src/views/LandingPages/SignIn/SignUp/SignUpView.vue
  src/views/Mypage/InfoUpdate/InfoAuthView.vue
  src/views/Mypage/InfoUpdate/InfoCompleteView.vue
  src/views/Mypage/InfoUpdate/InfoUpdateView.vue
  src/views/Mypage/InfoUpdate/PwAuthView.vue
  src/views/Mypage/InfoUpdate/PwUpdateView.vue
  src/views/Mypage/InfoUpdate/Sections/MemberInfoUpdate.vue
  src/views/Mypage/InfoUpdate/Sections/PWAuthView.vue
  src/views/Mypage/MypageView.vue
  src/views/Mypage/Resign/ResignCompleteView.vue
  src/views/Mypage/Resign/ResignView.vue
  src/views/Mypage/RoomReservationList/RoomReservationDetailView.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationDetailView.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
Labels: Frontend, Refactor

#198 [refactor/#192] 디자인 수정
  src/views/Presentation/PresentationView.vue
  src/views/Presentation/Sections/SearchRoom/RoomSearchForm.vue
  src/views/TicketOrders/TicketOrderView.vue
  src/views/TicketOrders/TicketResultView.vue
Labels: Frontend, Refactor

#201 [refactor/#200] 마이페이지 디자인 수정
  src/views/LandingPages/SignIn/Member/FindMemberID/IdAuthentication.vue
  src/views/LandingPages/SignIn/Sections/Authentication.vue
  src/views/LandingPages/SignIn/Sections/CorporateInfo.vue
  src/views/LandingPages/SignIn/Sections/MemberInfo.vue
  src/views/LandingPages/SignIn/Sections/PwAuthentication.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
Labels: Design, Frontend

#202 [refactor/#199] Event, Accomodation List 페이지네이션
  src/stores/eventStore.js
  src/views/Presentation/Components/ExampleCard.vue
  src/views/Presentation/PresentationView.vue
  src/views/Presentation/Sections/Accommodation/AccommodationList.vue
  src/views/Presentation/Sections/Event/EventList.vue
Labels: Frontend, Refactor

#204 [refactor/#203] ThemePark 디자인 수정
  src/assets/img/footerLogo.png
  src/examples/footers/FooterDefault.vue
  src/views/Presentation/Sections/Accommodation/AccommodationList.vue
  src/views/Presentation/Sections/Event/EventList.vue
  src/views/ThemeParks/AttractionInfo.vue
  src/views/ThemeParks/MainImage.vue
  src/views/ThemeParks/ThemeParkInfo.vue
Labels: Frontend, Refactor

#206 [refactor/#205] 입장권 관련 페이지 디자인 수정
  src/components/TicketOrders/BuyerInfo.vue
  src/components/TicketOrders/ProductInfo.vue
  src/components/TicketOrders/UsageInfo.vue
  src/views/Events/EventsListView.vue
  src/views/Notices/NoticesListView.vue
  src/views/Suggestions/SuggestionsListView.vue
  src/views/TicketOrders/PriceInfos/PriceInfoWrapper.vue
  src/views/TicketOrders/PriceInfos/SeolakWaterpia.vue
  src/views/TicketOrders/TicketOrderView.vue
  src/views/TicketOrders/TicketSelectionView.vue
Labels: Frontend, Refactor
