Repository beyond-sw-camp/be08-fin-EasyCheck-EasyStay-front-client, pull requests merged in 2024-10, with the labels that each got.

#5 [design/#1] Header 디자인
  .eslintrc.cjs
  package.json
  src/App.vue
  src/examples/navbars/NavbarDefault.vue
  src/examples/tables/Table.vue
  src/main.js
  src/views/Presentation/PresentationView.vue
Labels: Design, Frontend

#8 [design/#7] 메인 페이지 디자인 수정
  src/assets/img/HanWhaResort.jpg
  src/assets/scss/material-kit/_cards.scss
  src/assets/scss/material-kit/_navbar.scss
  src/assets/scss/material-kit/bootstrap/_card.scss
  src/examples/Header.vue
  src/views/Presentation/PresentationView.vue
Labels: Design, Frontend

#9 [design/#6] 카카오맵 생성
  index.html
  src/components/map/KakaoMap.vue
  src/views/Presentation/PresentationView.vue
  vite.config.js
Labels: Design, Frontend

#11 [refactor/#10] KakaoMap 수정
  index.html
  package.json
  src/components/map/KakaoMap.vue
  src/main.js
Labels: Frontend, Refactor

#13 [design/#2] design/#2/LoginPage
  src/assets/scss/material-kit/custom/_styles.scss
  src/assets/scss/material-kit/forms/_form-check.scss
  src/assets/scss/material-kit/forms/_input-group.scss
  src/views/LandingPages/SignIn/BasicView.vue
Labels: Design, Frontend

#17 [design/#15] design/#15/CommonJoin
  src/views/LandingPages/SignIn/CorporateView.vue
  src/views/LandingPages/SignIn/JoinView.vue
  src/views/LandingPages/SignIn/MemberView.vue
Labels: Design, Frontend

#20 Design/#14/room detail
  src/assets/scss/material-kit/_nav.scss
  src/assets/scss/material-kit/_variables.scss
  src/assets/scss/material-kit/custom/_styles.scss
  src/assets/scss/material-kit/custom/_variables.scss
  src/router/index.js
  src/views/Accommodations/AccommodationView.vue
  src/views/Accommodations/Sections/AccommodationInfo.vue
  src/views/Accommodations/Sections/AccomodationImage.vue
  src/views/Accommodations/Sections/EventInfo.vue
  src/views/Accommodations/Sections/RoomInfo.vue
  src/views/Rooms/RoomDetailView.vue
  src/views/Rooms/Sections/AdditionalService.vue
  src/views/Rooms/Sections/RoomImage.vue
  src/views/Rooms/Sections/RoomInfo.vue
  src/views/Rooms/Sections/RoomRates.vue
  src/views/Rooms/Sections/RoomTypeNavs.vue
Labels: Design, Frontend

#21 design: 일반회원 회원가입 페이지
  src/router/index.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/LandingPages/SignIn/JoinComplete.vue
  src/views/LandingPages/SignIn/JoinView.vue
  src/views/LandingPages/SignIn/MemberView.vue
Labels: Design, Frontend

#25 [refactor/#24] Navbar 디자인 수정 및 Router 처리
  src/examples/navbars/NavbarDefault.vue
  src/router/index.js
  src/views/LandingPages/SignIn/BasicView.vue
Labels: Frontend, Refactor

#28 [refactor/#27] refactor/#27/refactorLogin
  src/router/index.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/LandingPages/SignIn/SignUpView.vue
Labels: Design, Frontend, Refactor

#31 [refactor/#24] 메인 화면에 사용할 이미지 업데이트
  src/assets/img/main_images/Belvedere.jpg
  src/assets/img/main_images/ParadiseCity.jpeg
  src/assets/img/main_images/SanjungLake.jpeg
  src/assets/img/main_images/Signiel.jpeg
  src/assets/img/main_images/Sorano.jpg
  src/assets/img/main_images/ThePlaza.jpeg
Labels: Frontend, Refactor

#34 [design/#29] design/#29/FindId
  src/router/index.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/LandingPages/SignIn/FindID/FindIdView.vue
  src/views/LandingPages/SignIn/Sections/Authentication.vue
  src/views/LandingPages/SignIn/SignUp/CorporateView.vue
  src/views/LandingPages/SignIn/SignUp/JoinCompleteView.vue
  src/views/LandingPages/SignIn/SignUp/MemberView.vue
  src/views/LandingPages/SignIn/SignUp/SignUpView.vue
Labels: Design, Frontend

#42 [refactor/#41] 메인페이지 이미지 리스트 조회 수정
  src/examples/navbars/NavbarDefault.vue
  src/views/Presentation/PresentationView.vue
Labels: Design, Frontend, Refactor

#44 [refactor/#43] 오시는 길 부분 디자인 수정
  src/components/map/KakaoMap.vue
Labels: Design, Frontend, Refactor

#46 [design/#45] 메인 페이지에 Accommodation 리스트 불러오기
  src/views/Presentation/Components/ExampleCard.vue
  src/views/Presentation/PresentationView.vue
  src/views/Presentation/Sections/Accommodation/AccommodationList.vue
Labels: Design, Frontend

#48 [design/#47] 결제 페이지 띄우기
  index.html
  package.json
  src/components/Payment/Payment.vue
  src/views/Presentation/PresentationView.vue
Labels: Design, Frontend

#52 [feat/#51] 메인페이지에 Reservation 연동
  src/views/Presentation/PresentationView.vue
  src/views/Presentation/Sections/SearchRoom/RoomList.vue
  src/views/Presentation/Sections/SearchRoom/RoomSearchForm.vue
Labels: Feat, Frontend

#54 [feat/#53] 예약 정보 담아서 예약 페이지에 넘기기
  src/router/index.js
  src/views/Payment/ReservationPage.vue
  src/views/Presentation/PresentationView.vue
  src/views/Presentation/Sections/SearchRoom/RoomList.vue
Labels: Feat, Frontend

#56 [chore/#55/axios] axios 인스턴스 생성 및 인터셉터 설정
  src/api/index.js
  src/stores/accommodationStore.js
Labels: Feat, Frontend

#58 [design/#40] design/#40/CorporateSignUp
  index.html
  src/components/MaterialInput.vue
  src/router/index.js
  src/views/LandingPages/SignIn/Corporate/CorporateView.vue
  src/views/LandingPages/SignIn/Member/FindMemberID/FindIdAuthenticationView.vue
  src/views/LandingPages/SignIn/Member/FindMemberID/FindIdView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwAuthenticationView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/PwComplete.vue
  src/views/LandingPages/SignIn/Member/MemberAuthView.vue
  src/views/LandingPages/SignIn/Member/MemberView.vue
  src/views/LandingPages/SignIn/Sections/CorporateInfo.vue
  src/views/LandingPages/SignIn/Sections/MemberInfo.vue
  src/views/LandingPages/SignIn/SignUp/CorporateView.vue
  src/views/LandingPages/SignIn/SignUp/SignUpView.vue
Labels: Design, Frontend

#60 [fix/#59] fix/#59/IndexFix
  src/router/index.js
Labels: Fix, Frontend

#64 [design/#61] design/#61/MypageMain
  src/router/index.js
  src/views/Mypage/MypageView.vue
Labels: Design, Frontend

#67 [Design/#26/reservation] 예약 페이지 퍼블리싱
  package.json
  src/plugins/index.js
  src/router/index.js
  src/views/Presentation/PresentationView.vue
  src/views/Reservation/ReservationView.vue
  src/views/Reservation/Sections/AccommodationNavs.vue
  src/views/Reservation/Sections/ReservationCalendar.vue
  src/views/Reservation/Sections/ReservationForm.vue
  src/views/Reservation/Sections/ReservationInfo.vue
  src/views/Reservation/Sections/ReservationSummary.vue
  src/views/Reservation/Sections/ReservationSummaryNavbar.vue
  src/views/Reservation/Sections/RoomSelectionGrid.vue
Labels: Design, Frontend

#68 [design/#65] design/#65/InfoUpdate
  index.html
  src/assets/img/easystay.png
  src/router/index.js
  src/views/Mypage/InfoUpdate/InfoCompleteView.vue
  src/views/Mypage/InfoUpdate/InfoUpdateView.vue
  src/views/Mypage/InfoUpdate/Sections/MemberInfoUpdate.vue
  src/views/Mypage/MypageView.vue
Labels: Design, Frontend

#71 [design/#63] Footer 생성
  src/components/map/KakaoMap.vue
  src/examples/footers/FooterDefault.vue
  src/views/Presentation/PresentationView.vue
Labels: Design, Frontend

#72 [fix/#70] fix/#70/index.js 수정
  src/router/index.js
Labels: Feat, Frontend

#74 [design/#73] design/#73/PwUpdate
  src/router/index.js
  src/views/Mypage/InfoUpdate/PwUpdateView.vue
  src/views/Mypage/InfoUpdate/Sections/MemberInfoUpdate.vue
Labels: Design, Frontend

#80 [feat/#79] 결제 연동 성공
  src/components/Payment/Payment.vue
  src/stores/paymentStore.js
  src/views/Payment/ReservationPage.vue
  src/views/Presentation/PresentationView.vue
Labels: Feat, Frontend

#87 [refactor/#85] 예약, 결제 로직 한번에 실행
  src/components/Payment/Payment.vue
  src/views/Payment/ReservationPage.vue
Labels: Frontend, Refactor

#89 [feat/#88] 환불 기능 추가
  src/components/Payment/Payment.vue
  src/router/index.js
  src/views/Payment/PaymentPage.vue
  src/views/Payment/ReservationPage.vue
Labels: Feat, Frontend

#92 [design/#82] feat/#82/LoginAndVerification
  src/components/MaterialInput.vue
  src/stores/loginStore.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/LandingPages/SignIn/Member/MemberView.vue
  src/views/LandingPages/SignIn/Sections/MemberInfo.vue
Labels: Feat, Frontend

#95 [fix/#94] fix/#94/FooterFix
  src/views/Mypage/Resign/ResignView.vue
Labels: Design, Fix, Frontend

#86 [Design/#78/reservation-result] 예약 결과 화면 퍼블리싱
  src/App.vue
  src/assets/scss/material-kit/custom/_styles.scss
  src/router/index.js
  src/views/Accommodations/AccommodationView.vue
  src/views/Presentation/PresentationView.vue
  src/views/Reservation/ReservationResultView.vue
  src/views/Reservation/Sections/Caution.vue
  src/views/Reservation/Sections/LocationGuide.vue
  src/views/Reservation/Sections/ReservationInfo.vue
  src/views/Reservation/Sections/ReservationResult.vue
  src/views/Rooms/RoomDetailView.vue
Labels: Design, Frontend

#97 [design/#82] feat/#82/회원가입
  src/main.js
  src/stores/loginStore.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/LandingPages/SignIn/Member/MemberView.vue
  src/views/LandingPages/SignIn/Sections/MemberInfo.vue
Labels: Feat, Frontend

#100 [design/#91] 간편예약 컴포넌트 생성
  src/components/EasyReservation/easyReservation.vue
  src/views/Presentation/PresentationView.vue
Labels: Design, Frontend

#101 [design/#99] design/#99/로그인 페이지 디자인 수정, 비밀번호 유효성 검사 추가, 푸터 정리
  src/router/index.js
  src/stores/loginStore.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/LandingPages/SignIn/Member/MemberAuthView.vue
  src/views/LandingPages/SignIn/Member/MemberView.vue
  src/views/LandingPages/SignIn/Sections/MemberInfo.vue
  src/views/LandingPages/SignIn/SignUp/JoinCompleteView.vue
  src/views/LandingPages/SignIn/SignUp/SignUpView.vue
Labels: Feat, Design, Frontend

#96 design : 공지사항 페이지 퍼블리싱
  src/assets/img/003.png
  src/assets/img/004.png
  src/assets/img/006.png
  src/router/index.js
  src/views/Notices/NoticesListView.vue
  src/views/Suggestions/SuggestionsListView.vue
Labels: Design, Frontend

#103 [feat/#102] feat/#102/마이페이지 연동 및 로그아웃
  src/main.js
  src/router/index.js
  src/stores/loginStore.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/Mypage/MypageView.vue
  src/views/Presentation/PresentationView.vue
Labels: Feat, Frontend

#106 [feat/#105] feat/#105/LoginStatus
  src/stores/loginStore.js
  src/views/LandingPages/SignIn/BasicView.vue
Labels: Feat, Frontend

#108 refactor : 건의사항 페이지 헤더 추가
  src/views/Suggestions/SuggestionsListView.vue
Labels: Frontend, Refactor

#110 [feat/#104] feat/#104/비회원 로그인 삭제 및 마이페이지 회원정보수정 연동
  src/stores/loginStore.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/Mypage/InfoUpdate/Sections/MemberInfoUpdate.vue
Labels: Feat, Design, Frontend

#112 Design/#33/TicketOrderPage
  package.json
  src/App.vue
  src/components/Payment/TicketPayment.vue
  src/components/ThemePark/AttractionModal.vue
  src/components/TicketOrders/BuyerInfo.vue
  src/components/TicketOrders/PrivacyAgreementModal.vue
  src/components/TicketOrders/ProductInfo.vue
  src/components/TicketOrders/UsageInfo.vue
  src/plugins/index.js
  src/router/index.js
  src/stores/accommodationStore.js
  src/stores/attractionStore.js
  src/stores/index.js
  src/stores/themeparkStore.js
  src/stores/ticketStore.js
  src/stores/ticketorderStore.js
  src/stores/ticketpaymentStore.js
  src/views/ThemeParks/AttractionInfo.vue
  src/views/ThemeParks/MainImage.vue
  src/views/ThemeParks/NoticeInfo.vue
  src/views/ThemeParks/ThemeParkView.vue
  src/views/ThemeParks/UsageGuides/SeolakWaterpia.vue
  src/views/ThemeParks/UsageGuides/UsageGuideWrapper.vue
  src/views/TicketOrders/ProductInfo.vue
  src/views/TicketOrders/TicketOrderView.vue
  src/views/TicketOrders/TicketSelectionView.vue
  src/views/TicketPurchaseComplete/PurchaseCompleteView.vue
Labels: Feat, Design, Frontend

#113 design : 공지사항 상세 페이지 퍼블리싱
  src/router/index.js
  src/views/Notices/NoticeDetail.vue
  src/views/Notices/NoticesListView.vue
Labels: Design, Frontend

#115 [refactor/#90] 이벤트 리스트 수정
  src/views/Presentation/PresentationView.vue
  src/views/Presentation/Sections/Event/EventList.vue
Labels: Frontend, Refactor

#117 [feat/#116] 무통장 입금 결제 연동
  src/components/Payment/Payment.vue
  src/views/Payment/ReservationPage.vue
Labels: Feat, Frontend

#118 feat: 공지사항 목록 조회 기능 연동....중
  src/stores/notice.js
  src/views/Notices/NoticesListView.vue
Labels: Feat, Frontend

#120 [refactor/#119] 로그인 상태에 따라 Navbar 변경
  src/examples/navbars/NavbarDefault.vue
  src/router/index.js
Labels: Frontend, Refactor

#122 Design/#109/notice read page
  src/stores/notice.js
  src/views/Notices/NoticesListView.vue
Labels: Frontend, Refactor

#128 feat : 공지사항 상세 페이지 기능 연동
  src/router/index.js
  src/stores/notice.js
  src/views/Notices/NoticeDetail.vue
  src/views/Notices/NoticesListView.vue
Labels: Feat, Frontend

#131 refactor : 공지사항 상세 페이지 수정
  src/stores/notice.js
  src/views/Notices/NoticeDetail.vue
Labels: Feat, Frontend

#132 [desing/#130] design/#130/객실 예약 내역, 테마파크 예약 내역 조회 페이지 추가
  src/router/index.js
  src/stores/loginStore.js
  src/views/Mypage/MypageView.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
Labels: Design, Frontend

#135 design : 이벤트 목록 페이지 퍼블리싱
  src/assets/img/이벤트배너 1.png
  src/assets/img/이벤트배너 2.png
  src/assets/img/이벤트배너 3.png
  src/assets/img/이벤트배너 4.png
  src/router/index.js
  src/views/Events/EventsListView.vue
Labels: Design, Frontend

#124 [refactor/#121] 메인페이지 전체 수정
  src/components/Payment/Payment.vue
  src/examples/navbars/NavbarDefault.vue
  src/stores/eventStore.js
  src/views/Presentation/Sections/Accommodation/AccommodationList.vue
  src/views/Presentation/Sections/Event/EventList.vue
  src/views/Presentation/Sections/SearchRoom/RoomSearchForm.vue
Labels: Frontend, Refactor

#136 refactor : 이벤트배너 사진 수정
  src/assets/img/이벤트배너 2.png
  src/assets/img/이벤트배너 3.png
  src/assets/img/이벤트배너 4.png
  src/assets/img/이벤트배너 5.png
  src/views/Events/EventsListView.vue
Labels: Design, Frontend

#137 feat : 이벤트 목록 페이지 기능 연동
  src/stores/eventStore.js
  src/views/Events/EventsListView.vue
  src/views/Notices/NoticesListView.vue
  src/views/Presentation/Sections/Event/EventList.vue
Labels: Feat, Frontend

#140 [design/#75/ticket] Ticket 결제 기능 생성
  jsconfig.json
  src/App.vue
  src/components/Payment/TicketPayment.vue
  src/components/ThemePark/AttractionModal.vue
  src/components/TicketOrders/BuyerInfo.vue
  src/components/TicketOrders/PrivacyAgreementModal.vue
  src/components/TicketOrders/ProductInfo.vue
  src/router/index.js
  src/stores/accommodationStore.js
  src/stores/loginStore.js
  src/stores/themeparkStore.js
  src/stores/ticketStore.js
  src/stores/ticketpaymentStore.js
  src/views/ErrorPages/ThemeParkErrorPage.vue
  src/views/Payment/PaymentPage.vue
  src/views/ThemeParks/AttractionInfo.vue
  src/views/ThemeParks/ThemeParkInfo.vue
  src/views/ThemeParks/ThemeParkView.vue
  src/views/TicketOrders/TicketOrderView.vue
  src/views/TicketOrders/TicketSelectionView.vue
Labels: Design, Frontend

#141 design: 이벤트 상세 페이지 퍼블리싱
  src/router/index.js
  src/views/Events/EventDetail.vue
  src/views/Events/EventView.vue
  src/views/Events/EventsListView.vue
  src/views/Notices/NoticeDetail.vue
  src/views/Notices/NoticesListView.vue
Labels: Design, Frontend

#143 [Feat/#98/backend] 예약 로직 추가
  package.json
  src/App.vue
  src/main.js
  src/stores/accommodationStore.js
  src/stores/loginStore.js
  src/stores/reservationStore.js
  src/views/Presentation/PresentationView.vue
  src/views/Reservation/ReservationView.vue
  src/views/Reservation/Sections/AccommodationNavs.vue
  src/views/Reservation/Sections/ReservationCalendar.vue
  src/views/Reservation/Sections/ReservationForm.vue
  src/views/Reservation/Sections/ReservationInfo.vue
  src/views/Reservation/Sections/ReservationSummary.vue
  src/views/Reservation/Sections/ReservationSummaryNavbar.vue
  src/views/Reservation/Sections/RoomSelectionGrid.vue
Labels: Feat, Frontend

#145 [feat/#139] feat/#139/mypageRoomList
  src/stores/loginStore.js
  src/stores/paymentStore.js
  src/stores/reservationStore.js
  src/views/LandingPages/SignIn/Member/FindMemberID/FindIdAuthenticationView.vue
  src/views/LandingPages/SignIn/Sections/Authentication.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
Labels: Feat, Frontend

#146 [feat/#144/payment] 결제 연동
  src/router/index.js
  src/stores/paymentStore.js
  src/stores/reservationStore.js
  src/views/Payment/ReservationPage.vue
  src/views/Reservation/ReservationResultView.vue
  src/views/Reservation/ReservationView.vue
  src/views/Reservation/Sections/LocationGuide.vue
  src/views/Reservation/Sections/ReservationForm.vue
  src/views/Reservation/Sections/ReservationInfo.vue
  src/views/Reservation/Sections/ReservationResult.vue
Labels: Feat, Frontend

#147 [feat/#139] feat/#139/mypageRoomList
  src/stores/mypageStore.js
  src/stores/paymentStore.js
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
Labels: Feat, Frontend

#148 [feat/#144] 환불 메소드 생성
  src/components/Payment/TicketPayment.vue
  src/router/index.js
  src/views/TicketOrders/TicketOrderView.vue
  src/views/TicketOrders/TicketRefund.vue
Labels: Feat, Frontend

#150 [refactor/#149] Navbar 고정
  src/App.vue
  src/views/Mypage/InfoUpdate/InfoAuthView.vue
  src/views/Mypage/InfoUpdate/InfoUpdateView.vue
  src/views/Mypage/InfoUpdate/PwAuthView.vue
  src/views/Mypage/MypageView.vue
  src/views/Mypage/Resign/ResignView.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
  src/views/Notices/NoticeDetail.vue
  src/views/Notices/NoticesListView.vue
  src/views/ThemeParks/ThemeParkView.vue
  src/views/TicketOrders/TicketOrderView.vue
  src/views/TicketOrders/TicketSelectionView.vue
Labels: Frontend, Refactor

#153 [refactor/#152] 환불 기능 수정
  src/components/Payment/TicketPayment.vue
  src/views/TicketOrders/TicketRefund.vue
Labels: Frontend, Refactor

#155 [feat/#151] feat/#151/아이디 찾기 약관사항 추가 + 테마파크 객실 내역 조회 수정
  src/stores/ticketpaymentStore.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/LandingPages/SignIn/Member/FindMemberID/FindIdView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwAuthenticationView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwView.vue
  src/views/LandingPages/SignIn/Sections/Authentication.vue
  src/views/LandingPages/SignIn/Sections/MemberInfo.vue
  src/views/LandingPages/SignIn/Sections/Modal.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
Labels: Feat, Design, Frontend

#158 [refactor/#154] 메인페이지 수정
  src/views/Presentation/PresentationView.vue
  src/views/Presentation/Sections/Accommodation/AccommodationList.vue
  src/views/ThemeParks/ThemeParkView.vue
Labels: Frontend, Refactor

#159 [feat/#156] feat/#156/mypageRoomThemepark
  src/views/Mypage/MypageView.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
  src/views/Mypage/ThemeparkReservationList/ThemeparkReservationList.vue
Labels: Feat, Design, Frontend

#167 [design/#160] 인증 페이지 약관 자세히 보기 모달창 추가
  src/views/LandingPages/SignIn/Member/FindMemberID/FindIdAuthenticationView.vue
  src/views/LandingPages/SignIn/Member/FindMemberPW/FindPwAuthenticationView.vue
  src/views/LandingPages/SignIn/Sections/Authentication.vue
  src/views/LandingPages/SignIn/Sections/CorporateInfo.vue
  src/views/LandingPages/SignIn/Sections/MemberInfo.vue
  src/views/LandingPages/SignIn/Sections/Modal.vue
  src/views/Mypage/InfoUpdate/InfoAuthView.vue
  src/views/Mypage/InfoUpdate/PwAuthView.vue
  src/views/Mypage/InfoUpdate/Sections/MemberInfoUpdate.vue
Labels: Design, Frontend

#166 [feat/#161] 입장권 무통장 입금 기능 추가
  src/components/TicketOrders/BuyerInfo.vue
  src/stores/reservationStore.js
  src/views/Reservation/Sections/RoomSelectionGrid.vue
  src/views/TicketOrders/TicketOrderView.vue
Labels: Feat, Frontend

#171 design: 메뉴바 생성
  src/examples/footers/FooterDefault.vue
  src/examples/navbars/NavbarDefault.vue
  src/stores/eventStore.js
  src/stores/notice.js
Labels: Design, Frontend

#172 [refactor/#169] Footer, 객실쪽 표 Border 수정
  src/examples/footers/FooterDefault.vue
  src/views/Rooms/RoomDetailView.vue
  src/views/Rooms/Sections/RoomInfo.vue
  src/views/Rooms/Sections/RoomRates.vue
Labels: Design, Frontend, Refactor

#174 [feat/#173] 객실 예약 결제 시 로그인 필요
  src/examples/navbars/NavbarDefault.vue
  src/views/Reservation/Sections/ReservationForm.vue
Labels: Design, Frontend, Refactor

#175 [design/#168] 객실 예약 내역 상세보기 페이지
  src/router/index.js
  src/stores/reservationStore.js
  src/views/LandingPages/SignIn/BasicView.vue
  src/views/Mypage/RoomReservationList/RoomReservationDetailView.vue
  src/views/Mypage/RoomReservationList/RoomReservationList.vue
Labels: Design, Frontend
